### ISSUE TITLE
获取到的cv::Mat为[]

### ISSUE THREAD

**Issue by 898722279** [OwlHowlinMornSky/WGC-Capture-with-OpenCV#1]
获取到的cv::Mat为空，请问是什么原因呢？是不是使用方法不对？

**Comment by OwlHowlinMornSky** [comment]
你可以看一下 https://github.com/OwlHowlinMornSky/DDOA-DOAXVV-OPEN-ASSISTANT/blob/master/CoreDll/Helper.steps.cpp 的 179 行的 bool Helper::Step_WaitFor() 和 162 行的 bool Helper::Step_CopyMat(cv::Mat& target)。
这个库目前就是用来写 DDOA 的 ; )

**Comment by OwlHowlinMornSky** [comment]
添加了一个示例： #2

**Comment by OwlHowlinMornSky** [comment]
添加了一个更容易理解的示例: #3
